#!/bin/bash
echo -n "Enter the Project ID: "
read pid
echo -n "Enter the customer name: "
read cn

# Replace spaces with underscores
cn_dashes="${cn// /_}"
# get the folder name
foldername="$pid"_"$cn_dashes"

echo "=========================================================="
echo "[*] Great going to make this folder for you: " $foldername

if [ ! -d ./$foldername ]; then
  mkdir -p ./$foldername;
  echo "[*] Created " $foldername
  # Move copy of interlace commands.txt to project
  cd ./$foldername
  cp /home/chrisy/tools/Interlace/chrisy/commands.txt . 
fi
echo "=========================================================="

echo -n "Enter the targets: "
nano targets.txt

interlace -tL targets.txt -cL commands.txt
