#!/bin/bash
echo -e "\e[42mDownloading the latest live Malware infected URLS from URLHaus\e[0m"
sleep 1.5
cd /root/Documents/malsamples/urlhaus
wget -O samples.txt https://urlhaus.abuse.ch/downloads/text_online/
sleep 1.5 
echo "Parsing the download to show only .co.uk domains:"
grep "co.uk" samples.txt >> uk_$(date +%d-%m-%Y).txt 
sleep 1.5
echo "Removing the original download"
rm samples.txt
echo -e "\e[42m Job Done!!!\e[0m"

