#!/bin/bash
echo "Downloading the latest live URLS from URLHaus" 
cd /root/Documents/malsamples/urlhaus
wget -O samples.txt https://urlhaus.abuse.ch/downloads/text_online/
grep "co.uk" samples.txt >> uk_$(date +%F).txt 
rm samples.txt

